

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: ads
      POSTGRES_DB: ads_db
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
