# Generated by Django 5.2 on 2025-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0003_alter_exchangeproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('AWAITING', 'Ожидает'), ('ACCEPTED', 'Принята'), ('REJECTED', 'Отклонена')], default='AWAITING', max_length=50, verbose_name='Статус'),
        ),
    ]
